services:
  scrumboard:
    image: scrumboard-frontend
    build:
      context: scrum-board-view
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200

  # backend:
  #   image: scrumboard-backend
  #   build:
  #     context: scrum-board-api
  #     dockerfile: ./Dockerfile
  #   environment:
  #     NODE_ENV: production
  #     MONGO_URI: mongodb://database:27017/scrumboard
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - database
  
  database:
    image: scrumboard-db
    build:
      context: data
      dockerfile: ./Dockerfile
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017