services:
  scrumboard:
    image: scrumboard-frontend
    build:
      context: view
      dockerfile: ./Dockerfile
    ports:
      - 4200:4200

  backend:
    image: scrumboard-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      MONGO_URI: mongodb://database:27017/scrumboard
    ports:
      - 8000:8000
    depends_on:
      - database
  
  database:
    image: scrumboard-db
    build:
      context: data
      dockerfile: ./Dockerfile
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017